import { Inter } from "next/font/google";
import "./globals.css";
import "../../styles/darkThemeCalendar.scss";
import { ThemeProvider } from "@/components/theme-provider";
import { StoreProvider } from "@/components/store-provider";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import { Toaster } from "@/components/ui/sonner";
import { notFound } from "next/navigation";
const inter = Inter({ subsets: ["latin", "vietnamese"] });
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata = {
	title: "UET",
	description: "Generated by UET",
};

export function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
	if (!i18nConfig.locales.includes(locale)) {
		notFound();
	}
	return (
		<html lang={locale} dir={dir(locale)} suppressHydrationWarning>
			<head>
				<link
					rel='icon'
					type='image/png'
					href='/favicon-96x96.png'
					sizes='96x96'
				/>
				<link rel='icon' type='image/svg+xml' href='/favicon.svg' />
				<link rel='shortcut icon' href='/favicon.ico' />
				<link
					rel='apple-touch-icon'
					sizes='180x180'
					href='/apple-touch-icon.png'
				/>
				<meta name='apple-mobile-web-app-title' content='MyWebSite' />
				<link rel='manifest' href='/site.webmanifest' />
			</head>
			<body className={inter.className}>
				<StoreProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						<Toaster closeButton richColors />
						<NuqsAdapter>{children}</NuqsAdapter>
					</ThemeProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
